In [103]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
df = pd.read_csv('datasets/data.csv')

In [52]:
df.head()

        Entity code  Year  Access to electricity (% of population)
0  Afghanistan  AFG  2000                                 1.613591
1  Afghanistan  AFG  2001                                 4.074574
2  Afghanistan  AFG  2002                                 9.409158
3  Afghanistan  AFG  2003                                14.738506
4  Afghanistan  AFG  2004                                20.064968

In [110]:
df2 = pd.read_csv('datasets/DEMO_DS.csv')

In [112]:
display(df2)

,DEMO_IND,Indicator,LOCATION,Country,TIME,Time,Value,Flag Codes,Flags
0,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2016,2016,1.8,NaN,NaN
1,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2017,2017,1.7,NaN,NaN
2,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2018,2018,1.7,NaN,NaN
3,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2019,2019,1.7,NaN,NaN
4,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2020,2020,1.6,NaN,NaN
...,...,...,...,...,...,...,...,...,...
41386,SP_DYN_LE00_IN,"Life expectancy at birth, total (years)",GIB,Gibraltar,2016,2016,82.0,NaN,NaN
41387,SP_DYN_LE00_IN,"Life expectancy at birth, total (years)",GIB,Gibraltar,2017,2017,82.0,NaN,NaN
41388,SP_DYN_LE00_IN,"Life expectancy at birth, total (years)",GIB,Gibraltar,2018,2018,82.0,NaN,NaN
41389,SP_DYN_LE00_IN,"Life expectancy at birth, total (years)",GIB,Gibraltar,2019,2019,82.0,NaN,NaN
41390,SP_DYN_LE00_IN,"Life expectancy at birth, total (years)",GIB,Gibraltar,2020,2020,82.0,NaN,NaN

In [113]:
df2.rename(columns={'Time': 'Year'}, inplace=True)
df2.head()

,DEMO_IND,Indicator,LOCATION,Country,TIME,Year,Value,Flag Codes,Flags
0,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2016,2016,1.8,NaN,NaN
1,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2017,2017,1.7,NaN,NaN
2,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2018,2018,1.7,NaN,NaN
3,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2019,2019,1.7,NaN,NaN
4,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2020,2020,1.6,NaN,NaN

In [114]:
df2 = df2.drop('TIME', axis=1)

In [115]:
df2.rename(columns={'LOCATION': 'code'}, inplace=True)
df2.head()

,DEMO_IND,Indicator,code,Country,Year,Value,Flag Codes,Flags
0,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2016,1.8,NaN,NaN
1,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2017,1.7,NaN,NaN
2,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2018,1.7,NaN,NaN
3,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2019,1.7,NaN,NaN
4,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2020,1.6,NaN,NaN

In [116]:
df.rename(columns={'Code':'code'}, inplace=True)

In [117]:
df.head()

        Entity code  Year  Access to electricity (% of population)
0  Afghanistan  AFG  2000                                 1.613591
1  Afghanistan  AFG  2001                                 4.074574
2  Afghanistan  AFG  2002                                 9.409158
3  Afghanistan  AFG  2003                                14.738506
4  Afghanistan  AFG  2004                                20.064968

In [118]:
df2.head()

,DEMO_IND,Indicator,code,Country,Year,Value,Flag Codes,Flags
0,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2016,1.8,NaN,NaN
1,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2017,1.7,NaN,NaN
2,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2018,1.7,NaN,NaN
3,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2019,1.7,NaN,NaN
4,SP_DYN_TFRT_IN,"Fertility rate, total (births per woman)",AUS,Australia,2020,1.6,NaN,NaN

In [130]:
result = pd.merge(df, df2, on=["code", "Year"], how="left")
result.head()

,Entity,code,Year,Access to electricity (% of population),DEMO_IND,Indicator,Country,Value,Flag Codes,Flags
0,Afghanistan,AFG,2000,1.613591,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,2001,4.074574,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,2002,9.409158,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,2003,14.738506,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,2004,20.064968,NaN,NaN,NaN,NaN,NaN,NaN

In [120]:
display(result)

,Entity,code,Year,Access to electricity (% of population),DEMO_IND,Indicator,Country,Value,Flag Codes,Flags
0,Afghanistan,AFG,2000,1.613591,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,2001,4.074574,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,2002,9.409158,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,2003,14.738506,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,2004,20.064968,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
38577,Zimbabwe,ZWE,2020,52.747670,NY_GNP_MKTP_CN,GNI (current LCU),Zimbabwe,1.348148e+12,NaN,NaN
38578,Zimbabwe,ZWE,2020,52.747670,NY_GNP_PCAP_CN,GNI per capita (current LCU),Zimbabwe,8.603600e+04,NaN,NaN
38579,Zimbabwe,ZWE,2020,52.747670,PA_NUS_ATLS,DEC alternative conversion factor (LCU per US$),Zimbabwe,6.410000e+01,NaN,NaN
38580,Zimbabwe,ZWE,2020,52.747670,PA_NUS_FCRF,"Official exchange rate (LCU per US$, period av...",Zimbabwe,5.130000e+01,NaN,NaN
38581,Zimbabwe,ZWE,2020,52.747670,PA_NUS_PPPC_RF,Price level ratio of PPP conversion factor (GD...,Zimbabwe,7.000000e-01,NaN,NaN

In [121]:
result = result.drop('Country', axis=1)
result.head()

,Entity,code,Year,Access to electricity (% of population),DEMO_IND,Indicator,Value,Flag Codes,Flags
0,Afghanistan,AFG,2000,1.613591,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,2001,4.074574,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,2002,9.409158,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,2003,14.738506,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,2004,20.064968,NaN,NaN,NaN,NaN,NaN

In [122]:
result = result.drop('DEMO_IND', axis=1)
result.head()

,Entity,code,Year,Access to electricity (% of population),Indicator,Value,Flag Codes,Flags
0,Afghanistan,AFG,2000,1.613591,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,2001,4.074574,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,2002,9.409158,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,2003,14.738506,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,2004,20.064968,NaN,NaN,NaN,NaN

In [129]:
display(result)

Indicator  DEC alternative conversion factor (LCU per US$)  \
code Year
ABW  2016                                                1
     2017                                                1
     2018                                                1
     2019                                                1
     2020                                                1
...                                                    ...
ZWE  2016                                                1
     2017                                                1
     2018                                                1
     2019                                                1
     2020                                                1

Indicator  Fertility rate, total (births per woman)  GDP (constant LCU)  \
code Year
ABW  2016                                         1                   1
     2017                                         1                   1
     2018                                         1                   1
     2019                                         1                   1
     2020                                         1                   1
...                                             ...                 ...
ZWE  2016                                         1                   1
     2017                                         1                   1
     2018                                         1                   1
     2019                                         1                   1
     2020                                         1                   1

Indicator  GDP (current LCU)  GDP (current US$)  \
code Year
ABW  2016                  1                  1
     2017                  1                  1
     2018                  1                  1
     2019                  1                  1
     2020                  1                  1
...                      ...                ...
ZWE  2016                  1                  1
     2017                  1                  1
     2018                  1                  1
     2019                  1                  1
     2020                  1                  1

Indicator  GDP at market prices (constant 2010 US$)  \
code Year
ABW  2016                                         1
     2017                                         1
     2018                                         1
     2019                                         1
     2020                                         1
...                                             ...
ZWE  2016                                         1
     2017                                         1
     2018                                         1
     2019                                         1
     2020                                         1

Indicator  GDP deflator (base year varies by country)  GDP growth (annual %)  \
code Year
ABW  2016                                           1                      1
     2017                                           1                      1
     2018                                           1                      1
     2019                                           1                      1
     2020                                           1                      1
...                                               ...                    ...
ZWE  2016                                           1                      1
     2017                                           1                      1
     2018                                           1                      1
     2019                                           1                      1
     2020                                           1                      1

Indicator  GDP per capita (current LCU)  GDP per capita (current US$)  ...  \
code Year                                                              ...
ABW  2016                             1                             1  ...
     2017                             1                             1  ...
     2018                             1                             1  ...
     2019                             1                             1  ...
     2020                             1                             1  ...
...                                 ...                           ...  ...
ZWE  2016                             1                             1  ...
     2017                             1                             1  ...
     2018                             1                             1  ...
     2019                             1                             1  ...
     2020                             1                             1  ...

Indicator  Population aged 15-24 years (thousands)  \
code Year
ABW  2016                                        1
     2017                                        1
     2018                                        1
     2019                                        1
     2020                                        1
...                                            ...
ZWE  2016                                        1
     2017                                        1
     2018                                        1
     2019                                        1
     2020                                        1

Indicator  Population aged 25-64 years (thousands)   \
code Year
ABW  2016                                         1
     2017                                         1
     2018                                         1
     2019                                         1
     2020                                         1
...                                             ...
ZWE  2016                                         1
     2017                                         1
     2018                                         1
     2019                                         1
     2020                                         1

Indicator  Population aged 65 years or older (thousands)  \
code Year
ABW  2016                                              1
     2017                                              1
     2018                                              1
     2019                                              1
     2020                                              1
...                                                  ...
ZWE  2016                                              1
     2017                                              1
     2018                                              1
     2019                                              1
     2020                                              1

Indicator  Population growth (annual %)  \
code Year
ABW  2016                             1
     2017                             1
     2018                             1
     2019                             1
     2020                             1
...                                 ...
ZWE  2016                             1
     2017                             1
     2018                             1
     2019                             1
     2020                             1

Indicator  Poverty headcount ratio at $3.20 a day (PPP) (% of population)  \
code Year
ABW  2016                                                  0
     2017                                                  0
     2018                                                  0
     2019                                                  0
     2020                                                  0
...                                                      ...
ZWE  2016                                                  0
     2017                                                  1
     2018                                                  0
     2019                                                  1
     2020                                                  0

Indicator  Prevalence of HIV, total (% of population ages 15-49)  \
code Year
ABW  2016                                                  0
     2017                                                  0
     2018                                                  0
     2019                                                  0
     2020                                                  0
...                                                      ...
ZWE  2016                                                  1
     2017                                                  1
     2018                                                  1
     2019                                                  1
     2020                                                  1

Indicator  Price level ratio of PPP conversion factor (GDP) to market exchange rate  \
code Year
ABW  2016                                                  1
     2017                                                  1
     2018                                                  1
     2019                                                  1
     2020                                                  1
...                                                      ...
ZWE  2016                                                  1
     2017                                                  1
     2018                                                  1
     2019                                                  1
     2020                                                  1

Indicator  Rural population (% of total population)  \
code Year
ABW  2016                                         1
     2017                                         1
     2018                                         1
     2019                                         1
     2020                                         1
...                                             ...
ZWE  2016                                         1
     2017                                         1
     2018                                         1
     2019                                         1
     2020                                         1

Indicator  Total debt service (% of GNI)  Total population (thousands)
code Year
ABW  2016                              0                             1
     2017                              0                             1
     2018                              0                             1
     2019                              0                             1
     2020                              0                             1
...                                  ...                           ...
ZWE  2016                              1                             1
     2017                              1                             1
     2018                              1                             1
     2019                              1                             1
     2020                              1                             1

[1060 rows x 35 columns]

In [125]:
result = result[result.Year > 2015]

In [131]:
display(result)

,Entity,code,Year,Access to electricity (% of population),DEMO_IND,Indicator,Country,Value,Flag Codes,Flags
0,Afghanistan,AFG,2000,1.613591,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,2001,4.074574,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,2002,9.409158,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,2003,14.738506,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,2004,20.064968,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
38577,Zimbabwe,ZWE,2020,52.747670,NY_GNP_MKTP_CN,GNI (current LCU),Zimbabwe,1.348148e+12,NaN,NaN
38578,Zimbabwe,ZWE,2020,52.747670,NY_GNP_PCAP_CN,GNI per capita (current LCU),Zimbabwe,8.603600e+04,NaN,NaN
38579,Zimbabwe,ZWE,2020,52.747670,PA_NUS_ATLS,DEC alternative conversion factor (LCU per US$),Zimbabwe,6.410000e+01,NaN,NaN
38580,Zimbabwe,ZWE,2020,52.747670,PA_NUS_FCRF,"Official exchange rate (LCU per US$, period av...",Zimbabwe,5.130000e+01,NaN,NaN
38581,Zimbabwe,ZWE,2020,52.747670,PA_NUS_PPPC_RF,Price level ratio of PPP conversion factor (GD...,Zimbabwe,7.000000e-01,NaN,NaN

In [133]:
result=pd.pivot_table(result,index=['code','Year','Access to electricity (% of population)'],columns='Indicator',values='Value',aggfunc=len,fill_value=0)

In [134]:
display(result)

Indicator                                          DEC alternative conversion factor (LCU per US$)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                                             1
     2017 100.000000                                                                             1
     2018 100.000000                                                                             1
     2019 100.000000                                                                             1
     2020 100.000000                                                                             1
...                                                                                            ...
ZWE  2016 42.561730                                                                              1
     2017 44.178635                                                                              1
     2018 45.572647                                                                              1
     2019 46.781475                                                                              1
     2020 52.747670                                                                              1

Indicator                                          Fertility rate, total (births per woman)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                                      1
     2017 100.000000                                                                      1
     2018 100.000000                                                                      1
     2019 100.000000                                                                      1
     2020 100.000000                                                                      1
...                                                                                     ...
ZWE  2016 42.561730                                                                       1
     2017 44.178635                                                                       1
     2018 45.572647                                                                       1
     2019 46.781475                                                                       1
     2020 52.747670                                                                       1

Indicator                                          GDP (constant LCU)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                1
     2017 100.000000                                                1
     2018 100.000000                                                1
     2019 100.000000                                                1
     2020 100.000000                                                1
...                                                               ...
ZWE  2016 42.561730                                                 1
     2017 44.178635                                                 1
     2018 45.572647                                                 1
     2019 46.781475                                                 1
     2020 52.747670                                                 1

Indicator                                          GDP (current LCU)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                               1
     2017 100.000000                                               1
     2018 100.000000                                               1
     2019 100.000000                                               1
     2020 100.000000                                               1
...                                                              ...
ZWE  2016 42.561730                                                1
     2017 44.178635                                                1
     2018 45.572647                                                1
     2019 46.781475                                                1
     2020 52.747670                                                1

Indicator                                          GDP (current US$)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                               1
     2017 100.000000                                               1
     2018 100.000000                                               1
     2019 100.000000                                               1
     2020 100.000000                                               1
...                                                              ...
ZWE  2016 42.561730                                                1
     2017 44.178635                                                1
     2018 45.572647                                                1
     2019 46.781475                                                1
     2020 52.747670                                                1

Indicator                                          GDP at market prices (constant 2010 US$)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                                      1
     2017 100.000000                                                                      1
     2018 100.000000                                                                      1
     2019 100.000000                                                                      1
     2020 100.000000                                                                      1
...                                                                                     ...
ZWE  2016 42.561730                                                                       1
     2017 44.178635                                                                       1
     2018 45.572647                                                                       1
     2019 46.781475                                                                       1
     2020 52.747670                                                                       1

Indicator                                          GDP deflator (base year varies by country)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                                        1
     2017 100.000000                                                                        1
     2018 100.000000                                                                        1
     2019 100.000000                                                                        1
     2020 100.000000                                                                        1
...                                                                                       ...
ZWE  2016 42.561730                                                                         1
     2017 44.178635                                                                         1
     2018 45.572647                                                                         1
     2019 46.781475                                                                         1
     2020 52.747670                                                                         1

Indicator                                          GDP growth (annual %)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                   1
     2017 100.000000                                                   1
     2018 100.000000                                                   1
     2019 100.000000                                                   1
     2020 100.000000                                                   1
...                                                                  ...
ZWE  2016 42.561730                                                    1
     2017 44.178635                                                    1
     2018 45.572647                                                    1
     2019 46.781475                                                    1
     2020 52.747670                                                    1

Indicator                                          GDP per capita (current LCU)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                          1
     2017 100.000000                                                          1
     2018 100.000000                                                          1
     2019 100.000000                                                          1
     2020 100.000000                                                          1
...                                                                         ...
ZWE  2016 42.561730                                                           1
     2017 44.178635                                                           1
     2018 45.572647                                                           1
     2019 46.781475                                                           1
     2020 52.747670                                                           1

Indicator                                          GDP per capita (current US$)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                          1
     2017 100.000000                                                          1
     2018 100.000000                                                          1
     2019 100.000000                                                          1
     2020 100.000000                                                          1
...                                                                         ...
ZWE  2016 42.561730                                                           1
     2017 44.178635                                                           1
     2018 45.572647                                                           1
     2019 46.781475                                                           1
     2020 52.747670                                                           1

Indicator                                          ...  \
code Year Access to electricity (% of population)  ...
ABW  2016 100.000000                               ...
     2017 100.000000                               ...
     2018 100.000000                               ...
     2019 100.000000                               ...
     2020 100.000000                               ...
...                                                ...
ZWE  2016 42.561730                                ...
     2017 44.178635                                ...
     2018 45.572647                                ...
     2019 46.781475                                ...
     2020 52.747670                                ...

Indicator                                          Population aged 15-24 years (thousands)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                                     1
     2017 100.000000                                                                     1
     2018 100.000000                                                                     1
     2019 100.000000                                                                     1
     2020 100.000000                                                                     1
...                                                                                    ...
ZWE  2016 42.561730                                                                      1
     2017 44.178635                                                                      1
     2018 45.572647                                                                      1
     2019 46.781475                                                                      1
     2020 52.747670                                                                      1

Indicator                                          Population aged 25-64 years (thousands)   \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                                      1
     2017 100.000000                                                                      1
     2018 100.000000                                                                      1
     2019 100.000000                                                                      1
     2020 100.000000                                                                      1
...                                                                                     ...
ZWE  2016 42.561730                                                                       1
     2017 44.178635                                                                       1
     2018 45.572647                                                                       1
     2019 46.781475                                                                       1
     2020 52.747670                                                                       1

Indicator                                          Population aged 65 years or older (thousands)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                                           1
     2017 100.000000                                                                           1
     2018 100.000000                                                                           1
     2019 100.000000                                                                           1
     2020 100.000000                                                                           1
...                                                                                          ...
ZWE  2016 42.561730                                                                            1
     2017 44.178635                                                                            1
     2018 45.572647                                                                            1
     2019 46.781475                                                                            1
     2020 52.747670                                                                            1

Indicator                                          Population growth (annual %)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                          1
     2017 100.000000                                                          1
     2018 100.000000                                                          1
     2019 100.000000                                                          1
     2020 100.000000                                                          1
...                                                                         ...
ZWE  2016 42.561730                                                           1
     2017 44.178635                                                           1
     2018 45.572647                                                           1
     2019 46.781475                                                           1
     2020 52.747670                                                           1

Indicator                                          Poverty headcount ratio at $3.20 a day (PPP) (% of population)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                                               0
     2017 100.000000                                                                               0
     2018 100.000000                                                                               0
     2019 100.000000                                                                               0
     2020 100.000000                                                                               0
...                                                                                              ...
ZWE  2016 42.561730                                                                                0
     2017 44.178635                                                                                1
     2018 45.572647                                                                                0
     2019 46.781475                                                                                1
     2020 52.747670                                                                                0

Indicator                                          Prevalence of HIV, total (% of population ages 15-49)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                                               0
     2017 100.000000                                                                               0
     2018 100.000000                                                                               0
     2019 100.000000                                                                               0
     2020 100.000000                                                                               0
...                                                                                              ...
ZWE  2016 42.561730                                                                                1
     2017 44.178635                                                                                1
     2018 45.572647                                                                                1
     2019 46.781475                                                                                1
     2020 52.747670                                                                                1

Indicator                                          Price level ratio of PPP conversion factor (GDP) to market exchange rate  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                                               1
     2017 100.000000                                                                               1
     2018 100.000000                                                                               1
     2019 100.000000                                                                               1
     2020 100.000000                                                                               1
...                                                                                              ...
ZWE  2016 42.561730                                                                                1
     2017 44.178635                                                                                1
     2018 45.572647                                                                                1
     2019 46.781475                                                                                1
     2020 52.747670                                                                                1

Indicator                                          Rural population (% of total population)  \
code Year Access to electricity (% of population)
ABW  2016 100.000000                                                                      1
     2017 100.000000                                                                      1
     2018 100.000000                                                                      1
     2019 100.000000                                                                      1

In [135]:
import pandas as pd
import matplotlib.pyplot as plt

# Assuming you have a DataFrame named df
# Replace 'Dependent_Column' and 'Independent_Column' with the actual column names in your DataFrame

# Plotting a scatter plot
plt.scatter(result['GDP (current US$)'], result['Access to electricity (% of population)'])

# Adding labels and title
plt.xlabel('GDP (current US$)')
plt.ylabel('Access to electricity (% of population)')
plt.title('Scatter Plot: GDP (current US$) vs Access to electricity (% of population)')

# Display the plot
plt.show()

KeyError: 'Access to electricity (% of population)'

In [137]:
result['GDP growth (annual %)']

code  Year  Access to electricity (% of population)
ABW   2016  100.000000                                 1
      2017  100.000000                                 1
      2018  100.000000                                 1
      2019  100.000000                                 1
      2020  100.000000                                 1
                                                      ..
ZWE   2016  42.561730                                  1
      2017  44.178635                                  1
      2018  45.572647                                  1
      2019  46.781475                                  1
      2020  52.747670                                  1
Name: GDP growth (annual %), Length: 1060, dtype: int64