In [1]:
import pandas as pd

In [8]:
df = pd.read_csv('datasets/data.csv')

In [9]:
df.head(20)

         Entity Code  Year  Access to electricity (% of population)
0   Afghanistan  AFG  2000                                 1.613591
1   Afghanistan  AFG  2001                                 4.074574
2   Afghanistan  AFG  2002                                 9.409158
3   Afghanistan  AFG  2003                                14.738506
4   Afghanistan  AFG  2004                                20.064968
5   Afghanistan  AFG  2005                                25.390894
6   Afghanistan  AFG  2006                                30.718690
7   Afghanistan  AFG  2007                                36.051010
8   Afghanistan  AFG  2008                                42.400000
9   Afghanistan  AFG  2009                                46.740050
10  Afghanistan  AFG  2010                                42.700000
11  Afghanistan  AFG  2011                                43.222020
12  Afghanistan  AFG  2012                                69.100000
13  Afghanistan  AFG  2013                                68.290650
14  Afghanistan  AFG  2014                                89.500000
15  Afghanistan  AFG  2015                                71.500000
16  Afghanistan  AFG  2016                                97.700000
17  Afghanistan  AFG  2017                                97.700000
18  Afghanistan  AFG  2018                                96.616135
19  Afghanistan  AFG  2019                                97.700000